[build]
builder = "NIXPACKS"

[deploy]
startCommand = "java -Dserver.port=$PORT -Dspring.profiles.active=production -jar target/quiz-online-0.0.1-SNAPSHOT.jar"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
